import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Layout",
  description: "Generated by ONUR VARSAK",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      style={{
        backgroundColor: "#E4B7E5",
        height: "400px",
        padding: "100px",
      }}
    >
      Dashboard Layout
      {children}
    </div>
  );
}
