"use client";

import {
  useSelectedLayoutSegment,
  useSelectedLayoutSegments,
} from "next/navigation";
// import type { Metadata } from "next";

// Since This layout is a client component, we can't use Metadata

// export const metadata: Metadata = {
//   title: "Settings Layout",
//   description: "Generated by ONUR VARSAK",
// };

export default function SettingsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Layouts do not have access to the route segments below itself. To access all route segments, you can use useSelectedLayoutSegment or useSelectedLayoutSegments in a Client Component.
  const segment = useSelectedLayoutSegment();
  const segments = useSelectedLayoutSegments();

  console.log("segment", segment);
  console.log("segments", segments);

  return (
    <section
      style={{
        backgroundColor: "#CCA43B",
        height: "400px",
        padding: "100px",
      }}
    >
      Settings Layout
      {children}
    </section>
  );
}
