import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Route Layout",
  description: "Generated by ONUR VARSAK",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div
          style={{
            backgroundColor: "#8AB0AB",
            height: "100vh",
            padding: "100px",
          }}
        >
          Route Layout
          {children}
        </div>
      </body>
    </html>
  );
}
